### ISSUE TITLE
Another Wooded Kingdom Crash

### ISSUE THREAD

**Issue by GamesJam82** [CraftyBoss/SuperMarioOdysseyOnline#15] opened 2022-06-27 03:51 UTC
If you try going to Wooded Kingdom it sometimes crashes. [Crash Log](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/files/8988535/01687836751_0100000000010000.log)

**Comment by GamesJam82** [comment] 2022-07-10 06:38
Apparently if the maxplayers is over 7 then Wooded crashes.

**Comment by Fuzzy2319** [comment] 2022-11-17 20:02
duplicate of #4

**Comment by speyejack** [comment] 2023-09-03 04:28
Closed as duplicate

**Closed as completed by speyejack** 2023-09-03 04:28 UTC
